### ISSUE TITLE
Switch to Block Speak if ON does not seem to be working with a virtual switch

### ISSUE THREAD

**Issue by DWLaurie** [HubitatCommunity/Hubitat-BetterLaundryMonitor#13]
I am trying to set a switch to mute Echo Speaks because when the voltage changes in my location I am getting the verbal queues that cycle is complete. Under normal circumstances everything is fine, but if I have this virtual switch on and I expect that Better Laundry Monitor will not speak, but it does. Not sure that is going on here.

Versions:
BLM v1.4.4
BLM - PS v1.4.8
HE C-5 -  v2.2.7.128
ZEN-15 - FW 1.6
ES App v4.1.8.0
ES Dev v4.1.8.0
ES Soc v4.1.8.0
ES Ser v2.7.0

Everything reports as up to date as is possible

![2021-07-11 12_19_58-Better Laundry Monitor - Washer and 5 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/65001219/125204758-77c53b00-e244-11eb-8fe5-3825e9ba8ede.jpg)

![2021-07-11 12_23_47-Better Laundry Monitor - Mute - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/65001219/125204802-a17e6200-e244-11eb-98e0-fd67c2daedb2.jpg)

Not sure what else would be useful

**Comment by csteele-PD** [comment]
The switch blocks Speech Synthesis and Music Player, not Notifications.

The Code is:

private send(msg) {
	if (!msg) return // no message 
	if (textNotification) { textNotification*.deviceNotification(msg) }
	if (debugOutput) { log.debug "send: $msg" }
	if (state.blockItState) return // no noise please.
	if (speechOut) { speechOut*.speak(msg) }
	if (player){ player*.playText(msg) }
}

You can see that notification is sent, THEN the check on the Blocking switch (BlockItState) and then the two "speak" processes. I think in some ways it's semantics in that you're using Notifications to Speak vs Speaking to speak, but it's working as intended.

**Comment by DWLaurie** [comment]
Thank you! I was just re-reading the UI and realized my misinterpretation.
